export const ESCAPE_KEY = '$escape'
export const FUNCTION_KEY = '$f'
export const DELETE_KEY = '$d'
export const REPLACE_KEY = '$r'
export const SPLICE_KEY = '$s'
export const SWAP_KEY = '$w'
export const MULTI_KEY = '$m'
